import { DEFAULT_TUI_LANGUAGE, type TuiLanguage } from './tuiLanguage.js'

const enTuiText = {
    appTitle: 'Trans20',
    glossaryAgentTitle: 'Trans20 Inspection Agent',
    translationAgentTitle: 'Trans20 Translation Agent',
    scope: 'Scope',
    startMenu: {
        subtitle: 'Choose workflow',
        options: {
            glossary: 'Start Glossary',
            translation: 'Start Translation',
            settings: 'Settings',
            setupWizard: 'Setup Wizard',
        },
        prompt: 'Choose Start Glossary, Start Translation, Settings, or Setup Wizard.',
    },
    taskDialog: {
        glossaryTitle: 'Trans20 Glossary',
        translationTitle: 'Trans20 Translation',
        selectGlossaryTitle: 'Select Glossary',
        defaultPrompt: 'Select a task to resume, or create a new task.',
        emptyPrompt: 'No resumable task found.',
        noMatchingGlossary: 'No completed matching glossary task found.',
        selectGlossaryPrompt: 'Select a glossary task, or continue without one.',
        newTask: 'New task',
        noGlossary: 'No glossary',
        ok: 'OK',
        cancel: 'Cancel',
        changeDirectory: 'Change Dir',
        help: 'Enter confirms. Esc returns. d changes directory.',
    },
    configMismatch: {
        useTaskConfig: 'Use Task Config',
        back: 'Back',
        title: (taskCode: string) => `Config changed for task ${taskCode}`,
        message: 'Resume requires the config saved in this task.',
        moreDifferences: (count: number) => `${count} more difference(s) in log.`,
        help: 'Enter/u uses task config. Esc/Back returns.',
        difference: (field: string, currentValue: string, taskValue: string) => `${field}: current=${currentValue} task=${taskValue}`,
        remainingDifferences: (count: number) => `...and ${count} more.`,
        warning: (taskCode: string, differences: string) => [
            `Task ${taskCode} was created with a different config.`,
            'Resume is blocked unless you continue with the config saved in the task.',
            differences,
        ].filter(Boolean).join(' '),
    },
    taskComplete: {
        title: 'Task completed',
        translationMessage: 'Translation stages completed and export is ready.',
        glossaryMessage: 'Glossary stages completed.',
        nextStep: 'Return to the main menu to start or resume another task.',
        backToMenu: 'Back to Menu',
        help: 'Enter/click returns to the main menu.',
    },
    settings: {
        title: 'Settings',
        subtitle: 'Enter/click opens a secondary editor. Save writes config.json and preferences.json.',
        current: 'Current',
        value: 'Value',
        emptySecret: '(leave blank to keep existing key)',
        save: 'Save',
        back: 'Back',
        saved: 'Saved settings.',
        emptyValue: '(empty)',
        invalidValue: (label: string) => `Invalid ${label}.`,
        integerRequired: (label: string, nullable: boolean) => `${label} must be an integer${nullable ? ' or null' : ''}.`,
        nonEmptyRequired: (label: string) => `${label} cannot be empty.`,
        categories: {
            ui: 'UI',
            'model-api': 'Model/API',
            files: 'Files',
            glossary: 'Glossary',
            translation: 'Translation',
            runtime: 'Runtime',
        },
        fields: {
            tuiLanguage: { label: 'TUI language', description: 'Language used by the terminal UI.' },
            url: { label: 'Base URL', description: 'OpenAI-compatible API endpoint.' },
            key: { label: 'API Key', description: 'Stored masked in the UI; edit to replace it.' },
            model: { label: 'Model', description: 'Model name used for all agents.' },
            contextWindow: { label: 'Context window', description: 'Maximum context budget for model prompts.' },
            reasoningEffort: { label: 'Reasoning effort', description: 'Reasoning effort passed to compatible models.' },
            apiRetryAttempts: { label: 'API retries', description: 'Retry attempts for transient API failures.' },
            agentLifecycleMaxRestarts: { label: 'Agent restarts', description: 'Maximum lifecycle restarts after worker failures.' },
            manualTransFile: { label: 'ManualTrans file', description: 'ManualTrans JSON path relative to run directory.' },
            glossaryWorkerParallelism: { label: 'Worker parallelism', description: 'Glossary worker count.' },
            glossaryWorkerBatchSize: { label: 'Batch size', description: 'Keys per glossary worker batch.' },
            glossaryWorkerRecursionLimit: { label: 'Worker recursion', description: 'Glossary worker recursion limit.' },
            glossaryReviewEveryCompletedBatches: { label: 'Review cadence', description: 'Run review after this many completed batches.' },
            glossaryReviewRecursionLimit: { label: 'Review recursion', description: 'Glossary review agent recursion limit.' },
            enableGlossaryBatchTools: { label: 'Batch tools', description: 'Enable glossary batch submission tools.' },
            enableGlossaryTargetTermRevisionCheck: { label: 'Target revision check', description: 'Block Entry appends when the queried target Term changed.' },
            glossarySubmitSummaryMaxChars: { label: 'Summary chars', description: 'Maximum submitted summary characters, or null.' },
            glossarySubmitDeferredNotesMaxItems: { label: 'Deferred notes', description: 'Maximum deferred note items, or null.' },
            translationWorkerParallelism: { label: 'Worker parallelism', description: 'Translation worker count.' },
            translationWorkerBatchSize: { label: 'Batch size', description: 'Keys per translation worker batch.' },
            translationWorkerRecursionLimit: { label: 'Worker recursion', description: 'Translation worker recursion limit.' },
            enableTranslationMemorySearch: { label: 'Memory search', description: 'Enable translation memory search tool.' },
            enableCharacterGenderWarnings: { label: 'Gender warnings', description: 'Enable character context gender warnings.' },
            rollbackOnFailure: { label: 'Rollback failure', description: 'Rollback failed glossary lifecycle results before restart.' },
            enableRunLogs: { label: 'Run logs', description: 'Write per-run JSONL event logs.' },
            enableDebugLogs: { label: 'Debug logs', description: 'Write per-run debug JSONL event logs.' },
        },
    },
    setupWizard: {
        title: 'Setup Wizard',
        subtitle: 'Complete the initial setup before starting a workflow.',
        previous: 'Previous',
        next: 'Next',
        retest: 'Test Again',
        skipRecommended: 'Skip',
        applyRecommended: 'Use Recommended',
        finish: 'Finish',
        saved: 'Setup wizard completed.',
        help: 'Enter continues or edits selected fields. Left/Right moves between steps.',
        steps: {
            welcome: 'Welcome',
            api: 'API Settings',
            apiTest: 'API Test',
            recommended: 'Recommended',
            project: 'Project Preferences',
        },
        stepDescriptions: {
            welcome: 'Complete the basic setup, then start using Trans20.',
            api: 'Configure the OpenAI-compatible model endpoint.',
            apiTest: 'Send a small request to check model availability.',
            recommended: 'Apply a tested configuration set for advanced models.',
            project: 'Choose interface and project defaults.',
        },
        welcomeLines: [
            'Welcome to Trans 20, a powerful Agent-driven translation assistant.',
            'This wizard will help you set the options needed to start. Use Next to continue.',
            'You can reopen this wizard from the main menu.',
        ],
        recommendedLines: [
            'Use the recommended configuration set?',
            'Recommended configuration is a tested set of options that may produce stable results on advanced models.',
            'Whether you use it or not, you can change these options later in Settings.',
        ],
        apiTestIdle: 'The model test has not started yet.',
        apiTestRunning: 'Testing model...',
        apiTestSucceeded: 'Model test succeeded.',
        apiTestFailed: 'Model test failed. You can still continue.',
        apiTestContinue: 'Use Next to continue after reviewing the result.',
        apiTestResponse: (response: string) => `Response: ${response}`,
        apiTestError: (message: string) => `Error: ${message}`,
    },
    transcript: {
        user: 'You',
        assistant: 'Agent',
        tool: 'Tool',
        error: 'Error',
        system: 'System',
    },
    pane: {
        reviewAgent: 'Review Agent',
        worker: 'Worker',
        window: 'Window',
        batches: 'Batches',
        pending: 'Pending',
        lifecycle: 'Lifecycle',
        batch: 'Batch',
        filtered: 'Filtered',
        keys: 'Keys',
        tool: 'Tool',
        error: 'Error',
        summary: 'Summary',
        recentReviewActivity: 'Recent review activity',
        idle: 'idle',
        apiResponse: (status: string, contentType: string) => `API response: ${status} ${contentType}`,
        apiTransportError: 'API transport error',
        stream: (value: string) => `stream: ${value}`,
        unknown: 'unknown',
        requestId: (value: string) => `request-id: ${value}`,
        duration: (milliseconds: number) => `duration: ${milliseconds}ms`,
        diagnostic: (value: string) => `diagnostic: ${value}`,
        eventError: (value: string) => `error: ${value}`,
        attempt: (attempt: number, maxAttempts: number) => `attempt ${attempt}/${maxAttempts}`,
        retryable: (value: boolean) => `retryable: ${value ? 'yes' : 'no'}`,
        retryIn: (milliseconds: number) => `retry in: ${milliseconds}ms`,
        apiEvent: (status: string, attempt: string) => `API ${status}: ${attempt}`,
        workerAgents: 'Worker Agents',
        translationWorkerAgents: 'Translation Worker Agents',
    },
    states: {
        taskStatus: {
            running: 'running',
            interrupted: 'interrupted',
            completed: 'completed',
            failed: 'failed',
        },
        taskStage: {
            created: 'created',
            initializing: 'initializing',
            preflighting: 'preflighting',
            extracting: 'extracting',
            reviewing: 'reviewing',
            exporting: 'exporting',
            ready: 'ready',
        },
        paneStatus: {
            idle: 'idle',
            starting: 'starting',
            running: 'running',
            freezing: 'freezing',
            committing: 'committing',
            completed: 'completed',
            failed: 'failed',
        },
        toolStatus: {
            started: 'start',
            completed: 'done',
            failed: 'fail',
        },
    },
    status: {
        scroll: 'scroll',
        api: 'api',
        bottom: 'bottom',
        idle: 'idle',
        total: 'total',
    },
    help: {
        startMenu: 'Up/Down select. Enter opens. Ctrl+C twice exits.',
        setupWizard: 'Enter continues or edits selected fields. Left/Right moves between steps. Esc backs after first setup.',
        settings: 'Tab area. Left/Right switches columns or buttons. Up/Down select. Enter activates. Esc backs.',
        settingsEdit: 'Ctrl+V pastes. Tab buttons. Left/Right switches button. Enter activates. Esc cancels.',
        taskSelection: 'Up/Down select. Tab buttons. Left/Right switches button. Enter activates. Esc backs. d changes directory.',
        confirmConfig: 'Tab or Left/Right switches button. Enter activates. Esc backs.',
        taskComplete: 'Enter returns to the main menu. Ctrl+C twice exits.',
        selectDirectory: 'Ctrl+V pastes. Enter confirms directory. Esc backs. Ctrl+C twice exits.',
        // Currently dead code: Ask mode is disabled; kept for possible future reuse.
        ready: 'Ctrl+V pastes. Enter submits. Wheel follows cursor. Page scrolls log. Home/End jumps log. /dir changes scope. Esc clears input. Ctrl+C twice exits.',
        working: 'Wheel/Page scroll log. Esc is ignored while working. Ctrl+C twice exits.',
    },
    prompt: {
        checkingSetup: 'Checking setup...',
        initializing: 'Loading model config and agent...',
        translationPreflight: 'Translation preflight is working...',
        glossaryPreflight: 'Glossary preflight is working...',
        translationExtracting: 'Translation worker agents are translating...',
        glossaryExtracting: 'Glossary worker agents are extracting terms...',
        exporting: 'Exporting translated JSON...',
        // Currently dead code: Ask mode is disabled; kept for possible future reuse.
        running: 'Agent is working...',
        settings: 'Settings: Tab changes area, Enter/click opens editor.',
        setupWizard: 'Setup wizard: complete the steps, then finish to save.',
        settingsEdit: 'Editing setting: Enter confirms, Esc cancels.',
        selectingTask: 'Selecting task...',
        selectingGlossary: 'Selecting glossary...',
        confirmConfig: 'Confirm task config...',
        taskComplete: 'Task completed.',
        directory: (defaultDirectory: string) => `Directory [${defaultDirectory}]:`,
        // Currently dead code: Ask mode is disabled; kept for possible future reuse.
        ask: 'Ask',
    },
    message: {
        ctrlCAgain: 'Press Ctrl+C again within 2 seconds to exit.',
        ctrlCTwice: 'Press Ctrl+C twice to exit.',
        clipboardUnavailable: 'Clipboard text is unavailable.',
        loadingRunDirectory: (directory: string) => `Loading run directory: ${directory}`,
        projectReady: (directory: string) => `Trans20 ready. Scope: ${directory}`,
        runDirectory: (directory: string) => `Run directory: ${directory}`,
        chooseRunDirectory: (directory: string) => `Choose a new run directory. Current: ${directory}`,
        taskLine: (taskCode: string, resumed: boolean) => `Task: ${taskCode}${resumed ? ' (resumed)' : ' (new)'}`,
        glossaryLine: (taskCode: string|null) => `Glossary: ${taskCode ?? 'none'}`,
        outputLine: (directory: string) => `Output: ${directory}`,
        runLogLine: (filePath: string) => `Run log: ${filePath}`,
        debugLogLine: (filePath: string) => `Debug log: ${filePath}`,
        noCompletedGlossarySelectNoGlossary: 'No completed matching glossary task found. Select No glossary to continue.',
        selectGlossaryForTranslation: 'Select a glossary task for this translation run, or continue with no glossary.',
        translationPreflightStart: 'Running translation preflight before worker agents...',
        glossaryPreflightStart: 'Running glossary preflight before worker agents...',
        translationPreflightFailed: (message: string) => `Translation preflight failed: ${message}`,
        glossaryPreflightFailed: (message: string) => `Glossary preflight failed: ${message}`,
        translationWorkersStart: 'Running translation worker agents before export...',
        glossaryWorkersStart: 'Running glossary worker agents before completion...',
        translationWorkerFinished: (completed: number, total: number, failed: number, restored: number) => `Translation worker stage finished. Completed ${completed}/${total} pending batches, failed ${failed}, restored ${restored} already completed batches.`,
        glossaryWorkerFinished: (completed: number, total: number, failed: number, reviewsCompleted: number, reviewsFailed: number) => `Glossary worker stage finished. Completed ${completed}/${total} batches, failed ${failed}. Reviews completed ${reviewsCompleted}, failed ${reviewsFailed}.`,
        translationWorkerFailed: (failed: number) => `Translation worker stage failed ${failed} batch(es).`,
        glossaryWorkerFailed: (failedBatches: number, failedReviews: number) => `Glossary worker stage failed ${failedBatches} batch(es), ${failedReviews} review(s).`,
        exportingManualTrans: 'Exporting translated ManualTrans JSON...',
        translationReady: 'Translation stages completed and export is ready.',
        glossaryReady: 'Stages 1 and 2 completed.',
        // Currently dead code: Ask mode is disabled; kept for possible future reuse.
        emptyResponse: '(empty response)',
        incompleteLegacyConfig: (taskCode: string) => `Task ${taskCode} was created with an incomplete legacy config snapshot and cannot be resumed safely.`,
        apiRetry: (label: string, attempt: number, maxAttempts: number, message: string) => `API retry: ${label} attempt ${attempt}/${maxAttempts}. ${message}`,
        notDirectory: (directory: string) => `${directory} is not a directory.`,
        truncated: '... truncated in UI ...',
        truncatedWithLog: '... truncated in UI; full content is in logs ...',
    },
    report: {
        glossaryPreflightPlan: 'Glossary Preflight Plan',
        planId: 'Plan ID',
        created: 'Created',
        projectContext: 'Project context',
        domainHint: 'Domain hint',
        sourceTarget: 'Source -> Target',
        extractionPolicy: 'Extraction policy',
        termTypes: 'Term types',
        entryTypes: 'Entry types',
        defaults: 'Defaults',
        term: 'Term',
        entry: 'Entry',
        evidenceRequired: 'Evidence required',
        oneEntryOneClaim: 'One entry one claim',
        yes: 'yes',
        no: 'no',
        focus: 'Focus',
        cautions: 'Cautions',
        notes: 'Notes',
        translationPreflight: 'Translation Preflight',
        submitted: 'Submitted',
        textProfile: 'Text profile',
        styleGuidance: 'Style guidance',
        formatProtection: 'Format protection',
        glossaryUsage: 'Glossary usage',
        contextUsage: 'Context usage',
        qualityCautions: 'Quality cautions',
        translationExportWritten: 'Translation export written',
        translatedValues: 'Translated values',
        preservedOriginalValues: 'Preserved original values',
    },
}

const zhTuiText = {
    appTitle: 'Trans20',
    glossaryAgentTitle: 'Trans20 检查 Agent',
    translationAgentTitle: 'Trans20 翻译 Agent',
    scope: '范围',
    startMenu: {
        subtitle: '选择工作流',
        options: {
            glossary: '开始术语表',
            translation: '开始翻译',
            settings: '设置',
            setupWizard: '设置向导',
        },
        prompt: '选择开始术语表、开始翻译、设置或设置向导。',
    },
    taskDialog: {
        glossaryTitle: 'Trans20 术语表',
        translationTitle: 'Trans20 翻译',
        selectGlossaryTitle: '选择术语表',
        defaultPrompt: '选择要恢复的任务，或创建新任务。',
        emptyPrompt: '没有可恢复任务。',
        noMatchingGlossary: '没有找到匹配的已完成术语表任务。',
        selectGlossaryPrompt: '选择一个术语表任务，或不使用术语表继续。',
        newTask: '新任务',
        noGlossary: '不使用术语表',
        ok: '确定',
        cancel: '取消',
        changeDirectory: '更改目录',
        help: 'Enter 确认。Esc 返回。d 更改目录。',
    },
    configMismatch: {
        useTaskConfig: '使用任务配置',
        back: '返回',
        title: (taskCode: string) => `任务 ${taskCode} 的配置已变化`,
        message: '恢复任务需要使用该任务保存的配置。',
        moreDifferences: (count: number) => `日志中还有 ${count} 个差异。`,
        help: 'Enter/u 使用任务配置。Esc/返回键返回。',
        difference: (field: string, currentValue: string, taskValue: string) => `${field}：当前=${currentValue} 任务=${taskValue}`,
        remainingDifferences: (count: number) => `...还有 ${count} 个。`,
        warning: (taskCode: string, differences: string) => [
            `任务 ${taskCode} 创建时使用了不同配置。`,
            '除非继续使用任务中保存的配置，否则不能安全恢复。',
            differences,
        ].filter(Boolean).join(' '),
    },
    taskComplete: {
        title: '任务已完成',
        translationMessage: '翻译阶段已完成，导出已就绪。',
        glossaryMessage: '术语表阶段已完成。',
        nextStep: '返回主菜单后可以开始或恢复其他任务。',
        backToMenu: '返回主菜单',
        help: 'Enter/点击返回主菜单。',
    },
    settings: {
        title: '设置',
        subtitle: 'Enter/点击打开二级编辑器。保存会写入 config.json 和 preferences.json。',
        current: '当前',
        value: '值',
        emptySecret: '(留空以保留现有 key)',
        save: '保存',
        back: '返回',
        saved: '设置已保存。',
        emptyValue: '(空)',
        invalidValue: (label: string) => `${label} 无效。`,
        integerRequired: (label: string, nullable: boolean) => `${label} 必须是整数${nullable ? '或 null' : ''}。`,
        nonEmptyRequired: (label: string) => `${label} 不能为空。`,
        categories: {
            ui: '界面',
            'model-api': '模型/API',
            files: '文件',
            glossary: '术语表',
            translation: '翻译',
            runtime: '运行时',
        },
        fields: {
            tuiLanguage: { label: 'TUI 语言', description: '终端界面使用的语言。' },
            url: { label: 'Base URL', description: 'OpenAI 兼容 API 端点。' },
            key: { label: 'API Key', description: '界面中会遮罩显示；编辑可替换。' },
            model: { label: '模型', description: '所有 agent 使用的模型名称。' },
            contextWindow: { label: '上下文窗口', description: '模型 prompt 的最大上下文预算。' },
            reasoningEffort: { label: '推理强度', description: '传给兼容模型的 reasoning effort。' },
            apiRetryAttempts: { label: 'API 重试', description: '瞬时 API 失败的重试次数。' },
            agentLifecycleMaxRestarts: { label: 'Agent 重启', description: 'worker 失败后的最大生命周期重启次数。' },
            manualTransFile: { label: 'ManualTrans 文件', description: '相对运行目录的 ManualTrans JSON 路径。' },
            glossaryWorkerParallelism: { label: 'Worker 并发', description: '术语表 worker 数量。' },
            glossaryWorkerBatchSize: { label: '批次大小', description: '每个术语表 worker 批次的 key 数。' },
            glossaryWorkerRecursionLimit: { label: 'Worker 递归', description: '术语表 worker 递归限制。' },
            glossaryReviewEveryCompletedBatches: { label: '审查间隔', description: '每完成这些批次后运行审查。' },
            glossaryReviewRecursionLimit: { label: '审查递归', description: '审查 agent 递归限制。' },
            enableGlossaryBatchTools: { label: '批量工具', description: '启用术语表批量提交工具。' },
            enableGlossaryTargetTermRevisionCheck: { label: '目标版本校验', description: '查询后的目标 Term 发生变化时阻止追加 Entry。' },
            glossarySubmitSummaryMaxChars: { label: '摘要字符', description: '提交摘要的最大字符数，或 null。' },
            glossarySubmitDeferredNotesMaxItems: { label: '延后备注', description: '延后备注的最大条目数，或 null。' },
            translationWorkerParallelism: { label: 'Worker 并发', description: '翻译 worker 数量。' },
            translationWorkerBatchSize: { label: '批次大小', description: '每个翻译 worker 批次的 key 数。' },
            translationWorkerRecursionLimit: { label: 'Worker 递归', description: '翻译 worker 递归限制。' },
            enableTranslationMemorySearch: { label: '翻译记忆搜索', description: '启用翻译记忆搜索工具。' },
            enableCharacterGenderWarnings: { label: '性别警告', description: '启用角色上下文性别警告。' },
            rollbackOnFailure: { label: '失败回滚', description: '重启前回滚失败的术语表生命周期结果。' },
            enableRunLogs: { label: '运行日志', description: '写入每次运行的 JSONL 事件日志。' },
            enableDebugLogs: { label: '调试日志', description: '写入每次运行的 debug JSONL 事件日志。' },
        },
    },
    setupWizard: {
        title: '设置向导',
        subtitle: '开始工作流前完成初始设置。',
        previous: '上一步',
        next: '下一步',
        retest: '再次测试',
        skipRecommended: '暂不使用',
        applyRecommended: '使用推荐配置',
        finish: '完成',
        saved: '设置向导已完成。',
        help: 'Enter 继续或编辑所选字段。左/右切换步骤。',
        steps: {
            welcome: '欢迎',
            api: 'API 设置',
            apiTest: 'API 测试',
            recommended: '推荐配置',
            project: '项目偏好',
        },
        stepDescriptions: {
            welcome: '完成基础设置后即可开始使用。',
            api: '配置 OpenAI 兼容模型端点。',
            apiTest: '发送一次小请求，检查模型是否可用。',
            recommended: '应用一组经过测试的配置项组合。',
            project: '选择界面和项目默认值。',
        },
        welcomeLines: [
            '欢迎来到 Trans 20，一个由 Agent 驱动的强力翻译助理。',
            '此向导会帮助您设置启动需要的相关选项。使用“下一步”继续。',
            '可从主菜单重新打开设置向导。',
        ],
        recommendedLines: [
            '使用推荐配置组合？',
            '『推荐配置』是一组经过测试的配置项组合，它可能会在先进模型上带来稳定的结果。',
            '无论您选择『推荐配置』与否，之后都可以在设置中修改。',
        ],
        apiTestIdle: '模型测试尚未开始。',
        apiTestRunning: '正在测试模型...',
        apiTestSucceeded: '模型测试成功。',
        apiTestFailed: '模型测试失败。您仍然可以继续。',
        apiTestContinue: '查看结果后可使用“下一步”继续。',
        apiTestResponse: (response: string) => `响应：${response}`,
        apiTestError: (message: string) => `错误：${message}`,
    },
    transcript: {
        user: '你',
        assistant: 'Agent',
        tool: '工具',
        error: '错误',
        system: '系统',
    },
    pane: {
        reviewAgent: '审查 Agent',
        worker: 'Worker',
        window: '窗口',
        batches: '批次',
        pending: '待处理',
        lifecycle: '生命周期',
        batch: '批次',
        filtered: '筛选范围',
        keys: '键',
        tool: '工具',
        error: '错误',
        summary: '摘要',
        recentReviewActivity: '最近审查活动',
        idle: '空闲',
        apiResponse: (status: string, contentType: string) => `API 响应：${status} ${contentType}`,
        apiTransportError: 'API 传输错误',
        stream: (value: string) => `流式：${value}`,
        unknown: '未知',
        requestId: (value: string) => `请求 ID：${value}`,
        duration: (milliseconds: number) => `耗时：${milliseconds}ms`,
        diagnostic: (value: string) => `诊断：${value}`,
        eventError: (value: string) => `错误：${value}`,
        attempt: (attempt: number, maxAttempts: number) => `第 ${attempt}/${maxAttempts} 次`,
        retryable: (value: boolean) => `可重试：${value ? '是' : '否'}`,
        retryIn: (milliseconds: number) => `${milliseconds}ms 后重试`,
        apiEvent: (status: string, attempt: string) => `API ${status}：${attempt}`,
        workerAgents: 'Worker Agent',
        translationWorkerAgents: '翻译 Worker Agent',
    },
    states: {
        taskStatus: {
            running: '运行中',
            interrupted: '已中断',
            completed: '已完成',
            failed: '失败',
        },
        taskStage: {
            created: '已创建',
            initializing: '初始化中',
            preflighting: '预检中',
            extracting: '抽取中',
            reviewing: '审查中',
            exporting: '导出中',
            ready: '就绪',
        },
        paneStatus: {
            idle: '空闲',
            starting: '启动中',
            running: '运行中',
            freezing: '冻结中',
            committing: '提交中',
            completed: '已完成',
            failed: '失败',
        },
        toolStatus: {
            started: '开始',
            completed: '完成',
            failed: '失败',
        },
    },
    status: {
        scroll: '滚动',
        api: 'API',
        bottom: '底部',
        idle: '空闲',
        total: '总计',
    },
    help: {
        startMenu: '上/下选择。Enter 打开。Ctrl+C 两次退出。',
        setupWizard: 'Enter 继续或编辑所选字段。左/右切换步骤。首次设置后 Esc 可返回。',
        settings: 'Tab 切换区域。左/右切换列或按钮。上/下选择。Enter 激活。Esc 返回。',
        settingsEdit: 'Ctrl+V 粘贴。Tab 切换按钮。左/右切换按钮。Enter 激活。Esc 取消。',
        taskSelection: '上/下选择。Tab 切换按钮。左/右切换按钮。Enter 激活。Esc 返回。d 更改目录。',
        confirmConfig: 'Tab 或左/右切换按钮。Enter 激活。Esc 返回。',
        taskComplete: 'Enter 返回主菜单。Ctrl+C 两次退出。',
        selectDirectory: 'Ctrl+V 粘贴。Enter 确认目录。Esc 返回。Ctrl+C 两次退出。',
        // Currently dead code: Ask mode is disabled; kept for possible future reuse.
        ready: 'Ctrl+V 粘贴。Enter 提交。滚轮跟随光标。Page 滚动日志。Home/End 跳转日志。/dir 更改范围。Esc 清空输入。Ctrl+C 两次退出。',
        working: '滚轮/Page 滚动日志。工作中忽略 Esc。Ctrl+C 两次退出。',
    },
    prompt: {
        checkingSetup: '正在检查设置...',
        initializing: '正在加载模型配置和 agent...',
        translationPreflight: '翻译预检正在运行...',
        glossaryPreflight: '术语表预检正在运行...',
        translationExtracting: '翻译 worker agent 正在翻译...',
        glossaryExtracting: '术语表 worker agent 正在抽取术语...',
        exporting: '正在导出翻译后的 JSON...',
        // Currently dead code: Ask mode is disabled; kept for possible future reuse.
        running: 'Agent 正在工作...',
        settings: '设置：Tab 切换区域，Enter/点击打开编辑器。',
        setupWizard: '设置向导：完成步骤后保存。',
        settingsEdit: '正在编辑设置：Enter 确认，Esc 取消。',
        selectingTask: '正在选择任务...',
        selectingGlossary: '正在选择术语表...',
        confirmConfig: '确认任务配置...',
        taskComplete: '任务已完成。',
        directory: (defaultDirectory: string) => `目录 [${defaultDirectory}]:`,
        // Currently dead code: Ask mode is disabled; kept for possible future reuse.
        ask: '提问',
    },
    message: {
        ctrlCAgain: '2 秒内再次按 Ctrl+C 退出。',
        ctrlCTwice: '按两次 Ctrl+C 退出。',
        clipboardUnavailable: '无法读取剪贴板文本。',
        loadingRunDirectory: (directory: string) => `正在加载运行目录：${directory}`,
        projectReady: (directory: string) => `Trans20 已就绪。范围：${directory}`,
        runDirectory: (directory: string) => `运行目录：${directory}`,
        chooseRunDirectory: (directory: string) => `选择新的运行目录。当前：${directory}`,
        taskLine: (taskCode: string, resumed: boolean) => `任务：${taskCode}${resumed ? '（恢复）' : '（新建）'}`,
        glossaryLine: (taskCode: string|null) => `术语表：${taskCode ?? '无'}`,
        outputLine: (directory: string) => `输出：${directory}`,
        runLogLine: (filePath: string) => `运行日志：${filePath}`,
        debugLogLine: (filePath: string) => `调试日志：${filePath}`,
        noCompletedGlossarySelectNoGlossary: '没有找到匹配的已完成术语表任务。选择“不使用术语表”继续。',
        selectGlossaryForTranslation: '为本次翻译选择一个术语表任务，或不使用术语表继续。',
        translationPreflightStart: '正在运行翻译预检，然后启动 worker agent...',
        glossaryPreflightStart: '正在运行术语表预检，然后启动 worker agent...',
        translationPreflightFailed: (message: string) => `翻译预检失败：${message}`,
        glossaryPreflightFailed: (message: string) => `术语表预检失败：${message}`,
        translationWorkersStart: '正在运行翻译 worker agent，然后导出...',
        glossaryWorkersStart: '正在运行术语表 worker agent，然后结束任务...',
        translationWorkerFinished: (completed: number, total: number, failed: number, restored: number) => `翻译 worker 阶段完成。完成 ${completed}/${total} 个待处理批次，失败 ${failed} 个，恢复 ${restored} 个已完成批次。`,
        glossaryWorkerFinished: (completed: number, total: number, failed: number, reviewsCompleted: number, reviewsFailed: number) => `术语表 worker 阶段完成。完成 ${completed}/${total} 个批次，失败 ${failed} 个。审查完成 ${reviewsCompleted} 次，失败 ${reviewsFailed} 次。`,
        translationWorkerFailed: (failed: number) => `翻译 worker 阶段失败 ${failed} 个批次。`,
        glossaryWorkerFailed: (failedBatches: number, failedReviews: number) => `术语表 worker 阶段失败 ${failedBatches} 个批次、${failedReviews} 次审查。`,
        exportingManualTrans: '正在导出翻译后的 ManualTrans JSON...',
        translationReady: '翻译阶段已完成，导出已就绪。',
        glossaryReady: '阶段 1 和阶段 2 已完成。',
        // Currently dead code: Ask mode is disabled; kept for possible future reuse.
        emptyResponse: '(空响应)',
        incompleteLegacyConfig: (taskCode: string) => `任务 ${taskCode} 使用不完整的旧版配置快照创建，无法安全恢复。`,
        apiRetry: (label: string, attempt: number, maxAttempts: number, message: string) => `API 重试：${label} 第 ${attempt}/${maxAttempts} 次。${message}`,
        notDirectory: (directory: string) => `${directory} 不是目录。`,
        truncated: '... UI 中已截断 ...',
        truncatedWithLog: '... UI 中已截断；完整内容在日志中 ...',
    },
    report: {
        glossaryPreflightPlan: '术语表预检计划',
        planId: '计划 ID',
        created: '创建时间',
        projectContext: '项目上下文',
        domainHint: '领域提示',
        sourceTarget: '源语言 -> 目标语言',
        extractionPolicy: '抽取策略',
        termTypes: '术语类型',
        entryTypes: '条目类型',
        defaults: '默认值',
        term: '术语',
        entry: '条目',
        evidenceRequired: '需要证据',
        oneEntryOneClaim: '一条目一声明',
        yes: '是',
        no: '否',
        focus: '重点',
        cautions: '注意事项',
        notes: '备注',
        translationPreflight: '翻译预检',
        submitted: '提交时间',
        textProfile: '文本画像',
        styleGuidance: '风格指导',
        formatProtection: '格式保护',
        glossaryUsage: '术语表用法',
        contextUsage: '上下文用法',
        qualityCautions: '质量注意事项',
        translationExportWritten: '翻译导出已写入',
        translatedValues: '已翻译值',
        preservedOriginalValues: '保留原文值',
    },
} satisfies typeof enTuiText

const tuiTexts = {
    en: enTuiText,
    'zh-CN': zhTuiText,
} satisfies Record<TuiLanguage, typeof enTuiText>

export type TuiText = typeof enTuiText

export function getTuiText (language: TuiLanguage = DEFAULT_TUI_LANGUAGE): TuiText {
    return tuiTexts[language]
}
